version: '3.4'

networks:
    sotagsapp:
      driver: bridge

services:
  sotagsdb:
    container_name: sotags-database
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=password12345#
    ports:
      - 1433:1433
    networks:
      - sotagsapp
 
  sotags:
    container_name: sotagsapp
    image: ${DOCKER_REGISTRY-}sotags
    build:
      context: .
      dockerfile: SOTags/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - sotagsdb
    environment:
      - DB_HOST=sotagsdb
      - DB_NAME=SOTagsApp
      - DB_SA_PASSWORD=password12345#
    networks:
      - sotagsapp